#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Feb  4 11:29:29 2018

@author: kyyevgomes
"""

#import libraries
import csv
import astropy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from astropy.visualization import astropy_mpl_style
plt.style.use(astropy_mpl_style)
from astropy import units as u
from astropy.coordinates import SkyCoord

#convert ra and dec
gd = pd.read_csv ('./data.csv', header=0)
c = SkyCoord(gd.ra*u.degree, gd.dec*u.degree, equinox='J2015.0')
gd['radecstring'] = c.to_string('hmsdms')
gd['radecstring']
gd['radecstring'].to_csv('./coordinates.tab', sep='\t', header=False, index=False)

#plot position of stars
plt.plot(gd['ra'],gd.dec,'ro')
plt.xlabel('Right Ascension')
plt.ylabel('Declination')
plt.gca().invert_xaxis()
plt.title('Position of Stars in Plaedies')
plt.show()

#plot color coded postion of stars
gd['dist']=[1./a for a in 0.001*gd['parallax']]
plt.scatter(gd.ra,gd.dec,c= gd.dist)#'ro'
plt.xlabel('Right Ascension')
plt.ylabel('Declination')
plt.gca().invert_xaxis()
plt.title('Position of Stars in Plaedies')
plt.show()

#print color coded V vs. BV diagram
bv = pd.read_csv ('./SIMBADpleiades.csv', header=0)
plt.scatter(bv.BV,bv.V,c=gd.dist)#'ro')
plt.xlabel('B-V')
plt.ylabel('V')
plt.gca().invert_yaxis()
plt.title('CMD')
plt.show()

#print data table
gd2 = pd.read_csv ('./data2.csv', header=0)
print(gd2)
